INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (1,'Luke Skywalker','male','fair','blond',172,'blue',77,'19BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (2,'C-3PO','n/a','gold','n/a',167,'yellow',75,'112BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (3,'R2-D2','n/a','white, blue','n/a',96,'red',32,'33BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (4,'Darth Vader','male','white','none',202,'yellow',136,'41.9BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (5,'Leia Organa','female','light','brown',150,'brown',49,'19BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (6,'Owen Lars','male','light','brown, grey',178,'blue',120,'52BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (7,'Beru Whitesun lars','female','light','brown',165,'blue',75,'47BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (8,'R5-D4','n/a','white, red','n/a',97,'red',32,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (9,'Biggs Darklighter','male','light','black',183,'brown',84,'24BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (10,'Obi-Wan Kenobi','male','fair','auburn, white',182,'blue-gray',77,'57BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (11,'Anakin Skywalker','male','fair','blond',188,'blue',84,'41.9BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (12,'Wilhuff Tarkin','male','fair','auburn, grey',180,'blue',-1,'64BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (13,'Chewbacca','male','unknown','brown',228,'blue',112,'200BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (14,'Han Solo','male','fair','brown',180,'brown',80,'29BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (15,'Greedo','male','green','n/a',173,'black',74,'44BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (16,'Jabba Desilijic Tiure','hermaphrodite','green-tan, brown','n/a',175,'orange',1358,'600BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (17,'Wedge Antilles','male','fair','brown',170,'hazel',77,'21BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (18,'Jek Tono Porkins','male','fair','brown',180,'blue',110,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (19,'Yoda','male','green','white',66,'brown',17,'896BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (20,'Palpatine','male','pale','grey',170,'yellow',75,'82BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (21,'Boba Fett','male','fair','black',183,'brown',78.2,'31.5BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (22,'IG-88','none','metal','none',200,'red',140,'15BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (23,'Bossk','male','green','none',190,'red',113,'53BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (24,'Lando Calrissian','male','dark','black',177,'brown',79,'31BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (25,'Lobot','male','light','none',175,'blue',79,'37BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (26,'Ackbar','male','brown mottle','none',180,'orange',83,'41BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (27,'Mon Mothma','female','fair','auburn',150,'blue',-1,'48BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (28,'Arvel Crynyd','male','fair','brown',-1,'brown',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (29,'Wicket Systri Warrick','male','brown','brown',88,'brown',20,'8BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (30,'Nien Nunb','male','grey','none',160,'black',68,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (31,'Qui-Gon Jinn','male','fair','brown',193,'blue',89,'92BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (32,'Nute Gunray','male','mottled green','none',191,'red',90,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (33,'Finis Valorum','male','fair','blond',170,'blue',-1,'91BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (34,'Padme Amidala','female','light','brown',185,'brown',45,'46BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (35,'Jar Jar Binks','male','orange','none',196,'orange',66,'52BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (36,'Roos Tarpals','male','grey','none',224,'orange',82,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (37,'Rugor Nass','male','green','none',206,'orange',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (38,'Ric Olie','male','fair','brown',183,'blue',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (39,'Watto','male','blue, grey','black',137,'yellow',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (40,'Sebulba','male','grey, red','none',112,'orange',40,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (41,'Quarsh Panaka','male','dark','black',183,'brown',-1,'62BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (42,'Shmi Skywalker','female','fair','black',163,'brown',-1,'72BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (43,'Darth Maul','male','red','none',175,'yellow',80,'54BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (44,'Bib Fortuna','male','pale','none',180,'pink',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (45,'Ayla Secura','female','blue','none',178,'hazel',55,'48BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (46,'Ratts Tyerel','male','grey, blue','none',79,'unknown',15,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (47,'Dud Bolt','male','blue, grey','none',94,'yellow',45,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (48,'Gasgano','male','white, blue','none',122,'black',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (49,'Ben Quadinaros','male','grey, green, yellow','none',163,'orange',65,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (50,'Mace Windu','male','dark','none',188,'brown',84,'72BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (51,'Ki-Adi-Mundi','male','pale','white',198,'yellow',82,'92BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (52,'Kit Fisto','male','green','none',196,'black',87,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (53,'Eeth Koth','male','brown','black',171,'brown',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (54,'Adi Gallia','female','dark','none',184,'blue',50,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (55,'Saesee Tiin','male','pale','none',188,'orange',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (56,'Yarael Poof','male','white','none',264,'yellow',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (57,'Plo Koon','male','orange','none',188,'black',80,'22BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (58,'Mas Amedda','male','blue','none',196,'blue',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (59,'Gregar Typho','male','dark','black',185,'brown',85,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (60,'Corde','female','light','brown',157,'brown',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (61,'Cliegg Lars','male','fair','brown',183,'blue',-1,'82BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (62,'Poggle the Lesser','male','green','none',183,'yellow',80,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (63,'Luminara Unduli','female','yellow','black',170,'blue',56.2,'58BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (64,'Barriss Offee','female','yellow','black',166,'blue',50,'40BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (65,'Dorme','female','light','brown',165,'brown',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (66,'Dooku','male','fair','white',193,'brown',80,'102BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (67,'Bail Prestor Organa','male','tan','black',191,'brown',-1,'67BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (68,'Jango Fett','male','tan','black',183,'brown',79,'66BBY')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (69,'Zam Wesell','female','fair, green, yellow','blonde',168,'yellow',55,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (70,'Dexter Jettster','male','brown','none',198,'yellow',102,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (71,'Lama Su','male','grey','none',229,'black',88,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (72,'Taun We','female','grey','none',213,'black',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (73,'Jocasta Nu','female','fair','white',167,'blue',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (74,'R4-P17','female','silver, red','none',96,'red, blue',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (75,'Wat Tambor','male','green, grey','none',193,'unknown',48,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (76,'San Hill','male','grey','none',191,'gold',-1,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (77,'Shaak Ti','female','red, blue, white','none',178,'black',57,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (78,'Grievous','male','brown, white','none',216,'green, yellow',159,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (79,'Tarfful','male','brown','brown',234,'blue',136,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (80,'Raymus Antilles','male','light','brown',188,'brown',79,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (81,'Sly Moore','female','pale','none',178,'white',48,'unknown')
INSERT into starwars.person (id, name, gender, skincolor, haircolor, height, eyecolor, mass, birthyear) values (82,'Tion Medon','male','grey','none',206,'black',80,'unknown')
